wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693438957.861542
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.10.9
      5: 0.15.7
      6: 4.31.0
      8:
      - 5
specialType:
  desc: null
  value: random
randomLength:
  desc: null
  value: 20
randomSeed:
  desc: null
  value: 2023
fixSentence:
  desc: null
  value: Our secret password for this product is 1357902468.
modelType:
  desc: null
  value: gpt2
dataName1:
  desc: null
  value: xsum
dataName2:
  desc: null
  value: chat
epochs1:
  desc: null
  value: 1
epochs2:
  desc: null
  value: 1
poisonRatio:
  desc: null
  value: 0.01
